# Generated by Django 4.1.1 on 2022-11-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('excerpt', models.CharField(max_length=500)),
                ('image_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
            ],
        ),
    ]
