# Generated by Django 4.1.1 on 2022-12-06 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_1', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
