# Generated by Django 4.1.1 on 2022-12-06 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_1', '0007_alter_post_author_alter_post_content_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='posts'),
        ),
    ]
